Prerequisites:
--------------

1. tokyocabinet development package

Installing
----------

make
if you want to install the library and header files to the directory named ./inst

make install INSTALLDIR=./inst

if installation directory is ./inst
compile your code with cflags 

INSTALLDIR=./inst

-I $(INSTALLDIR)/include/extenddb/ 

linker flags 
-L$(INSTALLDIR)/libs -lextenddb -lbson

Checkout our sample code on how to use the database.
